#!/bin/sh

### BEGIN INIT INFO
# Provides:          load-balancer
# Required-Start:    $local_fs $remote_fs $network $syslog
# Required-Stop:     $local_fs $remote_fs $network $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the load-balancer
# Description:       starts load-balancer
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/load-balancer.py
NAME=load-balancer
DESC=load-balancer

case "$1" in
	start)
		echo -n "Starting $DESC: "
		load-balancer.py start
		echo "$NAME."
		;;

	stop)
		echo -n "Stopping $DESC: "
		load-balancer.py stop
		echo "$NAME."
		;;

	restart|force-reload)
		echo -n "Restarting $DESC: "
		load-balancer.py restart
		echo "$NAME."
		;;

	*)
		echo "Usage: $NAME {start|stop|restart}" >&2
		exit 1
		;;
esac

exit 0